# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Check, build and deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
  build-dev:
    runs-on: ubuntu-latest
    environment: development
    steps:
    - name: Pull repo
      run: |
        git clone https://github.com/NotLawson/premierscodingchallenge.git
        cd premierscodingchallenge
    - name: Build dev container
      run: |
        echo {{secrets.TOKEN}} | docker login ghcr.io -u USERNAME --password-stdin
        docker build -t ghcr.io/notlawson/premierscodingchallenge:dev .
    - name: Push container
      run: | 
        docker push ghcr.io/notlawson/premierscodingchallenge:dev

  build-prod:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Pull repo
      run: |
        git clone https://github.com/NotLawson/premierscodingchallenge.git
        cd premierscodingchallenge
    - name: Build prod container
      run: |
        echo {{secrets.TOKEN}} | docker login ghcr.io -u USERNAME --password-stdin
        docker build -t ghcr.io/notlawson/premierscodingchallenge:latest .
    - name: Push container
      run: | 
        docker push ghcr.io/notlawson/premierscodingchallenge:latest